version: "3"

services:
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=practice.backsoul.xyz
      - LETSENCRYPT_HOST=practice.backsoul.xyz
      - LETSENCRYPT_EMAIL=danielsarmientoenterprise@gmail.com